### ISSUE TITLE
Completar listas

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#1]
Completar lista de:
- [ ] cidades e países
- [ ] sintomas
- [ ] comorbidades

**Comment by samuel0072** [comment]
Encontrei essa lista de países com 242 países no site https://www.downloadexcelfiles.com/pt-pt/wo_pt/lista-de-paises-do-mundo#.XoYCB4OSm00

- China
- Índia
- Estados Unidos
- Indonésia
- Brasil
- Paquistão
- Nigéria
- Bangladesh
- Rússia
- Japão
- México
- Filipinas
- Etiópia
- Vietname
- Egito
- Alemanha
- Turquia
- Irã
- República Democrática do Congo
- Tailândia
- França
- Reino Unido
- Itália
- Myanmar
- Coreia do Sul
- África do Sul
- Tanzânia
- Espanha
- Colômbia
- Ucrânia
- Quênia
- Argentina
- Polónia
- Argélia
- Sudão
- Uganda
- Canadá
- Marrocos
- Iraque
- Afeganistão
- Nepal
- Peru
- Malásia
- Uzbequistão
- Venezuela
- Arábia Saudita
- Gana
- Coreia do Norte
- Iémen/Iêmen
- Taiwan
- Moçambique
- Síria
- Madagáscar
- Roménia
- Austrália
- Costa do Marfim
- Sri Lanka
- Camarões
- Países Baixos
- Chile
- Cazaquistão
- Burkina Faso
- Níger
- Equador
- Camboja
- Malawi
- Senegal
- Guatemala
- Angola
- Mali
- Zâmbia
- Cuba
- Zimbabwe
- Grécia
- Portugal
- Bélgica
- Tunísia
- República Checa
- Ruanda
- Chade
- Hungria
- Guiné
- Bielorrússia
- Bolívia
- Somália
- República Dominicana
- Suécia
- Haiti
- Burundi
- Benim
- Sudão do Sul
- Áustria
- Azerbaijão
- Honduras
- Suíça
- Sérvia
- Bulgária
- Tajiquistão
- Israel
- El Salvador
- Hong Kong ( República Popular da China)
- Paraguai
- Laos
- Serra Leoa
- Jordânia
- Líbia
- Papua-Nova Guiné
- Togo
- Nicarágua
- Eritreia
- Dinamarca
- Eslováquia
- Quirguistão
- Finlândia
- Turquemenistão
- Noruega
- Geórgia
- Emirados Árabes Unidos
- Singapura
- Bósnia e Herzegovina
- Croácia
- República Centro-Africana
- Moldávia
- Costa Rica
- Nova Zelândia
- Irlanda
- Líbano
- Porto Rico
- República do Congo
- Albânia
- Lituânia
- Uruguai
- Libéria
- Omã
- Panamá
- Mauritânia
- Mongólia
- Arménia
- Jamaica
- Kuwait
- Cisjordânia
- Letônia
- Lesoto
- Namíbia
- Macedónia
- Eslovênia
- Botswana
- Kosovo
- Gâmbia
- Guiné-Bissau
- Faixa de Gaza
- Gabão
- Estónia
- Maurícia
- Trinidad e Tobago
- Suazilândia
- Timor-Leste
- Fiji
- Catar
- Chipre
- Guiana
- Comores
- Reunião ( França)
- Bahrein
- Butão
- Montenegro
- Guiné Equatorial
- Ilhas Salomão
- Macau ( República Popular da China)
- Djibouti
- Luxemburgo
- Guadalupe ( França)
- Suriname
- Martinica ( França)
- Cabo Verde
- Malta
- Saara Ocidental
- Maldivas
- Brunei
- Bahamas
- Islândia
- Belize
- Barbados
- Polinésia Francesa ( França)
- Madeira ( Portugal)
- Açores ( Portugal)
- Antilhas Holandesas ( Países Baixos)
- Nova Caledônia ( França)
- Samoa
- Maiote ( França)
- Vanuatu
- São Tomé e Príncipe
- Polinésia Francesa ( França)
- Santa Lúcia
- Curaçao ( Países Baixos)
- Tonga
- Kiribati
- Ilhas Virgens Americanas ( Estados Unidos)
- Estados Federados da Micronésia
- São Vicente e Granadinas
- Aruba ( Países Baixos)
- Jersey ( Reino Unido)
- Granada
- Marianas Setentrionais ( Estados Unidos)
- Seychelles
- Antígua e Barbuda
- Andorra
- Ilha de Man ( Reino Unido)
- Dominica
- Bermudas ( Reino Unido)
- Guernesei ( Reino Unido)
- Samoa Americana ( Estados Unidos)
- Ilhas Marshall
- Gronelândia ( Dinamarca)
- Ilhas Feroé ( Dinamarca)
- Ilhas Cayman ( Reino Unido)
- São Cristóvão e Nevis
- Liechtenstein
- Mónaco
- São Marino
- São Martinho ( França)
- Gibraltar ( Reino Unido)
- Ilhas Virgens Britânicas ( Reino Unido)
- Turcas e Caicos ( Reino Unido)
- Palau
- Wallis e Futuna ( França)
- Anguilla ( Reino Unido)
- Nauru
- Ilhas Cook ( Nova Zelândia)
- Tuvalu
- Santa Helena, Ascensão e Tristão da Cunha ( Reino Unido)
- São Pedro e Miquelão ( França)
- Montserrat ( Reino Unido)
- Ilhas Malvinas ou Malvinas ( Reino Unido)
- Svalbard e Jan Mayen ( Noruega)
- Niue ( Nova Zelândia)
- Ilha Norfolk ( Austrália)
- Toquelau ( Nova Zelândia)
- Vaticano
- Ilhas Cocos (Keeling) ( Austrália)
- Ilha do Natal ( Austrália)
- Pitcairn ( Reino Unido)

**Comment by barbosaaob** [comment]
> (Atualizei) Encontrei a lista de países em https://www.who.int/countries/en/
> (A lista está traduzida)

por favor, adicione ao choices.py do monitoring.
