### ISSUE TITLE
Exigir idade e cidade no cadastro do paciente

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#10]
Precisamos que cada paciente tenha pelo menos a idade e a cidade no endereço. Da pra chamar a tela de cadastro de endereço após finalizar o cadastro dos dados do usuário? Acho que pode ser o caminho menos trabalhoso.

**Comment by jhonnye0** [comment]
Com relação ao segundo problema acredito que não dê para resolver, ou está além de minhas capacidades, pois para chamar a tela de cadastro de endereço tem de existir um id de um profile já existente e não estou sabendo pegar o id do profile recém-criado.

**Comment by jhonnye0** [comment]
Já dei um commit relacionado ao status do paciente que também está incluso a modificação na idade, data de nascimento e cidade

**Comment by barbosaaob** [comment]
> não estou sabendo pegar o id do profile recém-criado.

avançou nisso?

**Comment by jhonnye0** [comment]
Sim, o cadastro do endereço está junto do profile, não dei commit ainda pois estou tentando corrigir a questao do script pra o cep
