### ISSUE TITLE
Informação de lotação das unidades de saúde no mapa

### ISSUE THREAD

**Issue by hugotallys** [LED-UFAL-Covid-19/smc19#14]
Adicionar informações de lotação das unidades de saúde para serem visualizadas no mapa:

- [x] Quantidade de leitos RET, UTI e respiradores disponível e total.
- [x] Aplicar mapa de calor refletindo a situação de lotação da unidade.

**Comment by barbosaaob** [comment]
Tem um bug no formulário de registro de leitos. (anexo)

![Anotação 2020-04-03 133257](https://user-images.githubusercontent.com/10778160/78388891-cd298b80-75af-11ea-865d-25a63b114198.png)

**Comment by hugotallys** [comment]
Corrigi. Tava comparando a string aí resolvi convertendo pra inteiro. Deve ter uma maneira mais adequada de fazer isso ... 

https://github.com/LED-UFAL-Covid-19/smc19/blob/cf26f8bdbdf0072a62ff79180b16d103f8b0fab4/prediction/views.py#L71

**Comment by hugotallys** [comment]
Como iremos mostrar as informações de recursos necessários no mapa? Ou essa informação vai ficar só na dashboard?

**Comment by barbosaaob** [comment]
Mapa só mostra casos, suspeitos e ocupação de leitos.
