### ISSUE TITLE
Alterar campo cidade no formulário

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#16]
Para evitar o nome da cidade inserido de diversas formas ou de formas erradas, é importante ter um dropdown menu com a lista de cidades noS formulárioS de endereço. Obviamente o script do cep tem que continuar funcionando.

**Comment by barbosaaob** [comment]
Lista de cidades já está no choices (c0812ad807a8318362600caa478ab5666be8fb0b)

**Comment by jhonnye0** [comment]
Como os nomes do choices.cities está diferente do valor retornado pela api de consulta do cep, está um tanto complicado conciliar os dois, provavelmente eu teria de renomear os nomes das cidades no choices.py mas tenho de saber quem mais está usando.

**Comment by barbosaaob** [comment]
> Como os nomes do choices.cities está diferente do valor retornado pela api de consulta do cep, está um tanto complicado conciliar os dois, provavelmente eu teria de renomear os nomes das cidades no choices.py mas tenho de saber quem mais está usando.

estou atualizando isso agora. vou fazer o push. me avisa se alguma cidade continuar diferente entre o choices e o script do cep.
