### ISSUE TITLE
Alterar campo de busca do paciente no atendimento

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#17]
Precisamos alterar esse dropdown por uma busca pelo nome do paciente. Num cenário com 100.000 pacientes cadastrados fica impossível achar alguma coisa ali.

![Anotação 2020-04-02 143240](https://user-images.githubusercontent.com/10778160/78286220-d3a3fe80-74ee-11ea-897f-d1d79ac837bb.png)

**Comment by samuel0072** [comment]
Eu coloquei ao lado do nome o cpf do paciente pra facilitar a diferenciar um paciente do outro caso eles tivessem mesmo nome.
