### ISSUE TITLE
Pesquisa do nome no atendimento não funciona corretamente

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#19]
A pesquisa pelo nome do paciente no formulário de atendimento só funciona se o nome exato for digitado. Precisamos de uma busca onde o nome parcial ou só o primeiro nome retorne as opções.

**Comment by samuel0072** [comment]
A busca por cpf, cns e rg devem funcionar como a busca por nome ou eles devem bater exatamente?

**Comment by barbosaaob** [comment]
A busca pode funcionar como a busca na página principal do atendimento.

**Comment by samuel0072** [comment]
certo, eu só tinha modificado mesmo o jeito que a busca por nome funciona
