### ISSUE TITLE
🚓🚨OPERAÇÃO LAVA CÓDIGO🚨🚓

### ISSUE THREAD

**Issue by valeriojr** [LED-UFAL-Covid-19/smc19#20]
Função (view) encontrada em [prediction/views.py](https://github.com/LED-UFAL-Covid-19/smc19/blob/master/prediction/views.py), linha 80. A rota também está sem segurança.

**Comment by valeriojr** [comment]
Ver comentário na linha 122 de monitoring/views.py

**Comment by hugotallys** [comment]
> Função (view) encontrada em [prediction/views.py](https://github.com/LED-UFAL-Covid-19/smc19/blob/master/prediction/views.py), linha 80. A rota também está sem segurança.

A função foi substituída pela classe:

https://github.com/LED-UFAL-Covid-19/smc19/blob/f2e4c92a467c1443a97537ffe4d36621c187edb4/prediction/views.py#L80

**Comment by barbosaaob** [comment]
Podemos fechar? @valeriojr

**Comment by valeriojr** [comment]
sim
