### ISSUE TITLE
Perfis de usuário

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#3]
vamos precisar de 3 perfis:

- perfil do atendente da unidade: pode cadastrar pacientes e fazer atendimentos. não precisa ter acesso a nenhuma outra funcionalidade do sistema. o perfil está associado a uma unidade de atendimento;
- perfil do administrados da unidade: pode cadastrar pacientes, fazer atendimentos, cadastrar pedido de material e leitos da unidade a qual ele está associado. não precisa ter acesso a outras funcionalidade como as visualizações;
- perfil da secretaria de saúde: tem acesso as visualizações e aos dashboards.

Duas coisas:

- O atendente do posto de saúde ou do hospital não tem como confirmar um caso, pois o teste vai pro laboratório e demora pra ter resposta. Nesse tempo o paciente pode não estar mais no posto ou hospital. Dessa forma, precisamos remover o campo de confirmação do formulário de atendimento (vamos manter o campo na base de dados com alterações).
- O comitê de gestão da crise recebe todas as respostas dos testes. Dessa forma, esse perfil deverá atualizar o resultado do teste.

**Comment by samuel0072** [comment]
Se não tiver algum problema eu irei trabalhar nessa issue agora.

**Comment by samuel0072** [comment]
Algumas perguntas

1ª - Como vai funcionar a inclusão de novos usuários no sistema? O perfil de administrador de uma unidade vai cadastrar perfis de atendentes da unidade e o perfil da secretaria de saúde vai cadastrar administradores de unidades?

2ª comitê de gestão da crise é um quarto perfil? Ou ele é o mesmo que algum dos outros 3? Se sim, qual? Se não, quais são todas as suas permissões?

**Comment by barbosaaob** [comment]
A inclusão dos usuários pode funcionar de acordo com a sua sugestão. O comitê gestor eh o mesmo que o perfil da secretaria de saúde.

**Comment by samuel0072** [comment]
Consertei a criação de usuários. Antes eles não estavam sendo salvos no banco. Ajeitei também o problema de não conseguir fazer login mesmo com o usuário criado. A senha estava sendo guardada sem hash
