### ISSUE TITLE
Quantidade de respiradores

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#8]
thales sugeriu adicionar a quantidade de respiradores (disponíveis e ocupados) de cada unidade de atendimento. da pra colocar junto do controle de leitos, basta adicionar mais esse campo pra que seja atualizado pelos administradores dos pontos de atendimento.

**Comment by valeriojr** [comment]
@hugotallys Confirma aí se já pode fechar essa
