### ISSUE TITLE
Previsão de demanda futura de leitos usando o histórico de confirmados

### ISSUE THREAD

**Issue by barbosaaob** [LED-UFAL-Covid-19/smc19#9]
Usar a tabela 1 do artigo do Imperial anexo para descobrir as faixas etárias y e as probabilidades p(y) e q(y). Se x(t) é o número de sintomáticos (definido pelo gestor de saúde) da classe y na data t, então

l(t) é o número de leitos necessários no dia t. o(t) é o número de leitos ocupados no dia t.

l(t) = c (s) * p(y)*x(t-2), onde p(y) é a probabilidade de paciente da faixa etária y se hospitalizar e c(s) é a divisão entre o número total de leitos do hospital s e o número total de leitos do estado.

u(t) é o número de leitos de utis necessários no dia t.

u(t) = c(s)*q(y)*o(t-6), onde q(y) é a probabilidade de paciente hospitalizado da faixa etária y ir para a uti.

Esses números l e u são previsões. Tem que colocar os reais para serem cadastrados pelo gestor numa parte específica, dia-a-dia.

---

https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf

---

Modelo SIR:

https://scipython.com/book/chapter-8-scipy/additional-examples/the-sir-epidemic-model/

```
import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# Total population, N.
N = 1000
# Initial number of infected and recovered individuals, I0 and R0.
I0, R0 = 1, 0
# Everyone else, S0, is susceptible to infection initially.
S0 = N - I0 - R0
# Contact rate, beta, and mean recovery rate, gamma, (in 1/days).
beta, gamma = 0.2, 1./10 
# A grid of time points (in days)
t = np.linspace(0, 160, 160)

# The SIR model differential equations.
def deriv(y, t, N, beta, gamma):
    S, I, R = y
    dSdt = -beta * S * I / N
    dIdt = beta * S * I / N - gamma * I
    dRdt = gamma * I
    return dSdt, dIdt, dRdt

# Initial conditions vector
y0 = S0, I0, R0
# Integrate the SIR equations over the time grid, t.
ret = odeint(deriv, y0, t, args=(N, beta, gamma))
S, I, R = ret.T

# Plot the data on three separate curves for S(t), I(t) and R(t)
fig = plt.figure(facecolor='w')
ax = fig.add_subplot(111, axis_bgcolor='#dddddd', axisbelow=True)
ax.plot(t, S/1000, 'b', alpha=0.5, lw=2, label='Susceptible')
ax.plot(t, I/1000, 'r', alpha=0.5, lw=2, label='Infected')
ax.plot(t, R/1000, 'g', alpha=0.5, lw=2, label='Recovered with immunity')
ax.set_xlabel('Time /days')
ax.set_ylabel('Number (1000s)')
ax.set_ylim(0,1.2)
ax.yaxis.set_tick_params(length=0)
ax.xaxis.set_tick_params(length=0)
ax.grid(b=True, which='major', c='w', lw=2, ls='-')
legend = ax.legend()
legend.get_frame().set_alpha(0.5)
for spine in ('top', 'right', 'bottom', 'left'):
    ax.spines[spine].set_visible(False)
plt.show()
```

---

População por faixa etária:

https://censo2010.ibge.gov.br/sinopse/index.php?uf=27&dados=26

```
# dados para alagoas. dados tambem estao disponiveis no link por municipio
idade = {
    "0-9":   137952+134131+152581+147534,
    "10-19": 156445+156547+170956+167207,
    "20-29": 130805+141199+140817+149240,
    "30-39": 100073+111840+117491+128978,
    "40-49": 76368+85274+91125+101962,
    "50-59": 51176+60372+62174+71484,
    "60-69": 30936+36630+41368+47640,
    "70-79": 13872+18675+21930+27457,
    "80+":   163+333+776+1229+2066+3195+4251+5881+8442+11919
}
```

**Comment by barbosaaob** [comment]
![populacao_idade](https://user-images.githubusercontent.com/10778160/78062995-7b89c280-735d-11ea-842c-385e85bb965e.png)

**Comment by juuze** [comment]
> Usar a tabela 1 do artigo do Imperial anexo para descobrir as faixas etárias y e as probabilidades p(y) e q(y). Se x(t) é o número de sintomáticos (definido pelo gestor de saúde) da classe y na data t, então
> 
> l(t) é o número de leitos necessários no dia t. o(t) é o número de leitos ocupados no dia t.
> 
> l(t) = c (s) * p(y)*x(t-2), onde p(y) é a probabilidade de paciente da faixa etária y se hospitalizar e c(s) é a divisão entre o número total de leitos do hospital s e o número total de leitos do estado.
> 
> u(t) é o número de leitos de utis necessários no dia t.
> 
> u(t) = c(s)*q(y)*o(t-6), onde q(y) é a probabilidade de paciente hospitalizado da faixa etária y ir para a uti.
> 
> Esses números l e u são previsões. Tem que colocar os reais para serem cadastrados pelo gestor numa parte específica, dia-a-dia.
> 
> https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf
> 
> Modelo SIR:
> 
> https://scipython.com/book/chapter-8-scipy/additional-examples/the-sir-epidemic-model/
> 
> ```
> import numpy as np
> from scipy.integrate import odeint
> import matplotlib.pyplot as plt
> 
> # Total population, N.
> N = 1000
> # Initial number of infected and recovered individuals, I0 and R0.
> I0, R0 = 1, 0
> # Everyone else, S0, is susceptible to infection initially.
> S0 = N - I0 - R0
> # Contact rate, beta, and mean recovery rate, gamma, (in 1/days).
> beta, gamma = 0.2, 1./10 
> # A grid of time points (in days)
> t = np.linspace(0, 160, 160)
> 
> # The SIR model differential equations.
> def deriv(y, t, N, beta, gamma):
>     S, I, R = y
>     dSdt = -beta * S * I / N
>     dIdt = beta * S * I / N - gamma * I
>     dRdt = gamma * I
>     return dSdt, dIdt, dRdt
> 
> # Initial conditions vector
> y0 = S0, I0, R0
> # Integrate the SIR equations over the time grid, t.
> ret = odeint(deriv, y0, t, args=(N, beta, gamma))
> S, I, R = ret.T
> 
> # Plot the data on three separate curves for S(t), I(t) and R(t)
> fig = plt.figure(facecolor='w')
> ax = fig.add_subplot(111, axis_bgcolor='#dddddd', axisbelow=True)
> ax.plot(t, S/1000, 'b', alpha=0.5, lw=2, label='Susceptible')
> ax.plot(t, I/1000, 'r', alpha=0.5, lw=2, label='Infected')
> ax.plot(t, R/1000, 'g', alpha=0.5, lw=2, label='Recovered with immunity')
> ax.set_xlabel('Time /days')
> ax.set_ylabel('Number (1000s)')
> ax.set_ylim(0,1.2)
> ax.yaxis.set_tick_params(length=0)
> ax.xaxis.set_tick_params(length=0)
> ax.grid(b=True, which='major', c='w', lw=2, ls='-')
> legend = ax.legend()
> legend.get_frame().set_alpha(0.5)
> for spine in ('top', 'right', 'bottom', 'left'):
>     ax.spines[spine].set_visible(False)
> plt.show()
> ```
> 
> População por faixa etária:
> 
> https://censo2010.ibge.gov.br/sinopse/index.php?uf=27&dados=26
> 
> ```
> # dados para alagoas. dados tambem estao disponiveis no link por municipio
> idade = {
>     "0-9":   137952+134131+152581+147534,
>     "10-19": 156445+156547+170956+167207,
>     "20-29": 130805+141199+140817+149240,
>     "30-39": 100073+111840+117491+128978,
>     "40-49": 76368+85274+91125+101962,
>     "50-59": 51176+60372+62174+71484,
>     "60-69": 30936+36630+41368+47640,
>     "70-79": 13872+18675+21930+27457,
>     "80+":   163+333+776+1229+2066+3195+4251+5881+8442+11919
> }
> ```

nao entendi onde entrar o histórico de confirmados na conta

**Comment by barbosaaob** [comment]
equipe de modelagem está trabalhando nisso.
